export type QuestionId = "business_type" | "primary_goal" | "enquiry_sources" | "response_speed" | "qualification_process" | "sales_follow_up_process" | "appointment_process" | "main_bottlenecks" | "time_consuming_tasks" | "automation_readiness";
export type Question = { id: QuestionId; title: string; hint?: string; type: "single" | "multi"; max?: number; answers: readonly { id: string; label: string }[] };
const a = (id: string, label: string) => ({ id, label });

export const questions: readonly Question[] = [
  { id: "business_type", title: "What best describes your business?", type: "single", answers: [a("professional_services_consulting", "Professional services or consulting"), a("coaching_training_education", "Coaching, training, or education"), a("property_finance_insurance", "Property, finance, or insurance"), a("healthcare_wellness_beauty", "Healthcare, wellness, or beauty"), a("home_repair_local_services", "Home, repair, or local services"), a("events_membership_community", "Events, membership, or community"), a("ecommerce_online_business", "E-commerce or online business"), a("agency_creative_marketing", "Agency, creative, or marketing services"), a("other", "Other")] },
  { id: "primary_goal", title: "Which business outcome is your highest priority right now?", type: "single", answers: [a("capture_enquiries_reduce_missed_opportunities", "Capture more enquiries and reduce missed opportunities"), a("identify_better_fit_leads_faster", "Identify better-fit leads faster"), a("convert_leads_with_consistent_follow_up", "Convert more leads into customers through consistent follow-up"), a("book_appointments_reduce_no_shows", "Book more appointments and reduce no-shows"), a("reduce_repetitive_customer_support_work", "Reduce repetitive customer support work"), a("improve_payment_collection_reduce_manual_chasing", "Improve payment collection and reduce manual chasing"), a("generate_reviews_reengage_inactive_customers", "Generate more reviews and re-engage inactive customers"), a("improve_workflow_visibility_reporting_coordination", "Improve workflow visibility, reporting, and coordination")] },
  { id: "enquiry_sources", title: "Where do most new enquiries currently come from?", hint: "Select all that apply.", type: "multi", answers: [a("website_forms", "Website forms"), a("landing_pages", "Landing pages"), a("whatsapp", "WhatsApp"), a("social_media_messages", "Social media messages"), a("phone_calls", "Phone calls"), a("email", "Email"), a("referrals", "Referrals"), a("events_qr_codes", "Events or QR codes"), a("online_advertising", "Online advertising"), a("other", "Other")] },
  { id: "response_speed", title: "How quickly do new enquiries usually receive a meaningful response?", type: "single", answers: [a("within_minutes", "Within a few minutes"), a("within_one_hour", "Within one hour"), a("within_same_working_day", "Within the same working day"), a("next_working_day", "The next working day"), a("depends_on_staff", "It depends on staff availability"), a("missed_completely", "Some enquiries are missed completely")] },
  { id: "qualification_process", title: "How are new leads currently assessed before your team spends time on them?", type: "single", answers: [a("clear_qualification_criteria", "We use clear qualification questions and criteria"), a("staff_qualify_manually_consistently", "Staff qualify leads manually and consistently"), a("staff_qualify_varies", "Staff qualify leads, but the process varies"), a("basic_contact_details_only", "We collect only basic contact details"), a("speak_to_almost_every_lead", "We speak to almost every lead before knowing whether they are suitable"), a("no_qualification_process", "We do not have a qualification process")] },
  { id: "sales_follow_up_process", title: "What usually happens when a prospect does not respond or decide immediately?", type: "single", answers: [a("consistent_multi_step_process", "A consistent multi-step follow-up process begins"), a("staff_follow_up_crm", "Staff follow up using reminders or a CRM"), a("staff_follow_up_when_remember", "Staff follow up manually when they remember"), a("follow_up_once", "We usually follow up only once"), a("follow_up_inconsistent", "Follow-up is inconsistent"), a("no_further_follow_up", "Most quiet leads receive no further follow-up")] },
  { id: "appointment_process", title: "How important are appointments, consultations, demonstrations, or calls in your sales process?", type: "single", answers: [a("essential_well_automated", "Essential, and booking is already well automated"), a("essential_manual_work", "Essential, but booking and reminders require manual work"), a("important_cancellations_no_shows", "Important, but we experience cancellations or no-shows"), a("sometimes_used", "Sometimes used, depending on the lead"), a("not_part_of_sales", "Not part of our sales process")] },
  { id: "main_bottlenecks", title: "Which problems currently create the most work or lost opportunities?", hint: "Select up to three.", type: "multi", max: 3, answers: [a("repetitive_enquiry_questions", "Repetitive enquiry questions"), a("slow_responses_outside_hours", "Slow responses outside business hours"), a("too_many_unsuitable_leads", "Too many unsuitable leads"), a("leads_going_cold", "Leads going cold"), a("manual_appointment_booking", "Manual appointment booking"), a("appointment_reminders_rescheduling", "Appointment reminders and rescheduling"), a("repetitive_customer_support_requests", "Repetitive customer support requests"), a("outstanding_invoices_payment_chasing", "Outstanding invoices or payment chasing"), a("too_few_reviews", "Too few customer reviews"), a("inactive_leads_past_customers", "Inactive leads or past customers not returning"), a("manual_reporting_scattered_information", "Manual reporting and scattered information"), a("tasks_handovers_missed", "Tasks or handovers being missed")] },
  { id: "time_consuming_tasks", title: "Which activities consume the most founder or staff time?", hint: "Select up to three.", type: "multi", max: 3, answers: [a("replying_to_new_enquiries", "Replying to new enquiries"), a("asking_qualification_questions", "Asking qualification questions"), a("following_up_with_leads", "Following up with leads"), a("booking_rescheduling_appointments", "Booking or rescheduling appointments"), a("answering_customer_questions", "Answering customer questions"), a("sending_invoices_payment_reminders", "Sending invoices or payment reminders"), a("requesting_reviews", "Requesting reviews"), a("re_engaging_inactive_contacts", "Re-engaging inactive contacts"), a("updating_spreadsheets_crm_records", "Updating spreadsheets or CRM records"), a("preparing_reports", "Preparing reports"), a("assigning_tasks_notifying_staff", "Assigning tasks and notifying staff")] },
  { id: "automation_readiness", title: "How prepared is your business to automate these processes?", type: "single", answers: [a("processes_clearly_documented", "Our processes and rules are clearly documented"), a("mostly_clear_not_documented", "Our processes are mostly clear but not documented"), a("different_staff_handle_differently", "Different staff handle the same task differently"), a("depends_on_one_person", "Many processes depend on one person"), a("clarify_before_automating", "We need to clarify the process before automating it"), a("not_sure", "I am not sure")] },
] as const;

export type Answers = Record<QuestionId, string[]>;
export const emptyAnswers = Object.fromEntries(questions.map((q) => [q.id, []])) as unknown as Answers;
