import { test, expect } from "@playwright/test";

test("landing to secure saved report with retained navigation", async ({ page }) => {
  await page.goto("/"); await expect(page.getByRole("heading",{name:/Find the right/})).toBeVisible(); await page.getByRole("link",{name:/Start the diagnostic/}).click(); await page.getByRole("button",{name:/Begin assessment/}).click();
  const choices=["Professional services or consulting","Capture more enquiries and reduce missed opportunities","Website forms","Some enquiries are missed completely","We collect only basic contact details","Follow-up is inconsistent","Essential, but booking and reminders require manual work"];
  for(const choice of choices){ await page.getByRole("button",{name:choice}).click(); await page.getByRole("button",{name:/Continue/}).click(); }
  for(const choice of ["Slow responses outside business hours","Leads going cold","Manual appointment booking"]){ await page.getByRole("button",{name:choice}).click(); } await page.getByRole("button",{name:/Continue/}).click();
  for(const choice of ["Replying to new enquiries","Following up with leads","Booking or rescheduling appointments"]){ await page.getByRole("button",{name:choice}).click(); } await page.getByRole("button",{name:/Back/}).click(); await expect(page.getByRole("button",{name:"Slow responses outside business hours"})).toHaveAttribute("aria-pressed","true"); await page.getByRole("button",{name:/Continue/}).click(); await expect(page.getByRole("button",{name:"Replying to new enquiries"})).toHaveAttribute("aria-pressed","true"); await page.getByRole("button",{name:/Continue/}).click();
  await page.getByRole("button",{name:"Our processes are mostly clear but not documented"}).click(); await page.getByRole("button",{name:/Continue/}).click(); await page.getByLabel(/First name/).fill("E2E"); await page.getByLabel(/Email address/).fill(`e2e-${Date.now()}@example.com`); await page.getByLabel(/Business name/).fill("Phase Two Test"); await page.getByText("Required report consent").click(); await page.getByRole("button",{name:/Generate my report/}).click(); await expect(page).toHaveURL(/\/report\/[a-f0-9]{64}$/); await expect(page.getByText("Submission saved securely")).toBeVisible();
  const token=page.url().split("/").pop()!; const response=await page.request.get(`/api/report/${token}`); expect(response.ok()).toBeTruthy(); const saved=await response.json(); expect(saved.public_report_token).toBe(token); expect(Object.keys(saved.agent_scores)).toHaveLength(8);
});
