import { test, expect } from "@playwright/test";

test("landing to complete secure AI Workforce Fit Report", async ({ page, context }) => {
  await page.goto("/"); await expect(page.getByRole("heading",{name:/Find the right/})).toBeVisible(); await page.getByRole("link",{name:/Start the diagnostic/}).click(); await page.getByRole("button",{name:/Begin assessment/}).click();
  const choices=["Professional services or consulting","Capture more enquiries and reduce missed opportunities","Website forms","Some enquiries are missed completely","We collect only basic contact details","Follow-up is inconsistent","Essential, but booking and reminders require manual work"];
  for(const choice of choices){ await page.getByRole("button",{name:choice}).click(); await page.getByRole("button",{name:/Continue/}).click(); }
  for(const choice of ["Slow responses outside business hours","Leads going cold","Manual appointment booking"]){ await page.getByRole("button",{name:choice}).click(); } await page.getByRole("button",{name:/Continue/}).click();
  for(const choice of ["Replying to new enquiries","Following up with leads","Booking or rescheduling appointments"]){ await page.getByRole("button",{name:choice}).click(); } await page.getByRole("button",{name:/Back/}).click(); await expect(page.getByRole("button",{name:"Slow responses outside business hours"})).toHaveAttribute("aria-pressed","true"); await page.getByRole("button",{name:/Continue/}).click(); await expect(page.getByRole("button",{name:"Replying to new enquiries"})).toHaveAttribute("aria-pressed","true"); await page.getByRole("button",{name:/Continue/}).click();
  await page.getByRole("button",{name:"Our processes are mostly clear but not documented"}).click(); await page.getByRole("button",{name:/Continue/}).click(); await page.getByLabel(/First name/).fill("E2E"); await page.getByLabel(/Email address/).fill(`e2e-${Date.now()}@example.com`); await page.getByLabel(/Business name/).fill("Phase Three Test"); await page.getByText("Required report consent").click(); await page.getByRole("button",{name:/Generate my report/}).click(); await expect(page).toHaveURL(/\/report\/[a-f0-9]{64}$/);
  await expect(page.getByRole("heading",{name:/A practical AI Workforce for Phase Three Test/})).toBeVisible();
  const topThree=["AI Enquiry Assistant","Sales Follow-Up Agent","Appointment Coordinator"]; for(const [index,name] of topThree.entries()){ await expect(page.locator(".recommendation-card").nth(index)).toContainText(name); }
  await expect(page.locator(".score-item")).toHaveCount(8); await expect(page.getByRole("heading",{name:"Start with Basic Process Setup"})).toBeVisible(); await expect(page.getByRole("heading",{name:"Roles to consider later"})).toBeVisible();
  const token=page.url().split("/").pop()!; const response=await page.request.get(`/api/report/${token}`); expect(response.ok()).toBeTruthy(); const saved=await response.json(); expect(saved.businessName).toBe("Phase Three Test"); expect(saved.scoreOverview).toHaveLength(8); expect(saved.topThree.map((item:{name:string})=>item.name)).toEqual(topThree); expect(saved.nextPhase).toHaveLength(2);
  const body=await page.locator("body").innerText(); for(const hidden of ["e2e-","report_processing_consent","enquiry_assistant",token]) expect(body).not.toContain(hidden);
  await context.grantPermissions(["clipboard-read","clipboard-write"],{origin:"http://127.0.0.1:3000"}); await page.getByRole("button",{name:"Copy report link"}).click(); await expect(page.getByRole("status")).toHaveText("Report link copied."); expect(await page.evaluate(()=>navigator.clipboard.readText())).toBe(page.url());
  await expect(page.getByRole("button",{name:"Print report"})).toBeVisible(); const reportUrl=page.url(); await page.reload(); await expect(page).toHaveURL(reportUrl); await expect(page.getByRole("heading",{name:/A practical AI Workforce for Phase Three Test/})).toBeVisible();
});
