create table if not exists submissions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  public_report_token text unique not null default replace(gen_random_uuid()::text, '-', '') || replace(gen_random_uuid()::text, '-', ''),

  first_name text not null,
  last_name text,
  email text not null,
  phone text,
  business_name text not null,
  website text,

  report_processing_consent boolean not null default false,
  report_processing_consent_at timestamptz,
  marketing_consent boolean not null default false,
  marketing_consent_at timestamptz,

  business_type text not null,
  primary_goal text not null,
  enquiry_sources text[],
  response_speed text,
  qualification_process text,
  sales_follow_up_process text,
  appointment_process text,
  main_bottlenecks text[],
  time_consuming_tasks text[],
  automation_readiness text,

  agent_scores jsonb,
  recommendation_1 text,
  recommendation_2 text,
  recommendation_3 text,
  next_phase_1 text,
  next_phase_2 text,
  tie_break_data jsonb,

  workforce_summary text,
  workforce_summary_source text,
  workforce_summary_confidence numeric,
  workforce_summary_review_status text default 'unreviewed',

  recommendation_content jsonb,
  recommendation_content_source text,
  recommendation_content_confidence numeric,
  recommendation_content_review_status text default 'unreviewed',

  workforce_sequence text,
  workforce_sequence_source text,
  workforce_sequence_confidence numeric,
  workforce_sequence_review_status text default 'unreviewed',

  readiness_notes text,
  readiness_notes_source text,
  readiness_notes_confidence numeric,
  readiness_notes_review_status text default 'unreviewed',

  next_phase_content jsonb,
  next_phase_content_source text,
  next_phase_content_confidence numeric,
  next_phase_content_review_status text default 'unreviewed',

  full_report_content jsonb,

  report_generation_status text not null default 'pending',
  report_generation_error text,
  report_generated_at timestamptz,

  crm_sync_status text not null default 'not_started',
  crm_sync_error text,
  crm_last_attempt_at timestamptz,
  crm_synced_at timestamptz,
  external_contact_id text
);

alter table submissions enable row level security;

drop policy if exists "submissions_v1_read" on submissions;
create policy "submissions_v1_read" on submissions for select using (true);

drop policy if exists "submissions_v1_write" on submissions;
create policy "submissions_v1_write" on submissions for all using (true) with check (true);

insert into submissions (
  public_report_token, first_name, last_name, email, phone, business_name, website,
  report_processing_consent, report_processing_consent_at, marketing_consent, marketing_consent_at,
  business_type, primary_goal, enquiry_sources, response_speed, qualification_process,
  sales_follow_up_process, appointment_process, main_bottlenecks, time_consuming_tasks,
  automation_readiness, agent_scores, recommendation_1, recommendation_2, recommendation_3,
  next_phase_1, next_phase_2, tie_break_data,
  workforce_summary, workforce_summary_source, workforce_summary_confidence, workforce_summary_review_status,
  recommendation_content, recommendation_content_source, recommendation_content_confidence, recommendation_content_review_status,
  workforce_sequence, workforce_sequence_source, workforce_sequence_confidence, workforce_sequence_review_status,
  readiness_notes, readiness_notes_source, readiness_notes_confidence, readiness_notes_review_status,
  next_phase_content, next_phase_content_source, next_phase_content_confidence, next_phase_content_review_status,
  full_report_content, report_generation_status, report_generated_at, crm_sync_status
) values
(
  'demo_token_alpha_001', 'Sarah', 'Mitchell', 'sarah@brightleafcoaching.com', '07700900001', 'Brightleaf Coaching', 'brightleafcoaching.com',
  true, now() - interval '2 days', true, now() - interval '2 days',
  'coaching_training_education', 'respond_to_enquiries_faster',
  ARRAY['website_forms','social_media_messages','referrals'],
  'depends_on_staff', 'basic_contact_details_only', 'follow_up_once',
  'essential_manual_work', ARRAY['slow_responses_outside_hours','leads_going_cold','repetitive_enquiry_questions'],
  ARRAY['replying_to_new_enquiries','following_up_with_leads','booking_rescheduling_appointments'],
  'mostly_clear_not_documented',
  '{"enquiry_assistant":14,"lead_qualification":9,"sales_follow_up":13,"appointment_coordinator":10,"customer_support":5,"payment_follow_up":3,"review_reactivation":4,"operations_reporting":6}',
  'enquiry_assistant', 'sales_follow_up', 'appointment_coordinator',
  'lead_qualification', 'operations_reporting',
  '{"method":"bottleneck_match","applied":false}',
  'Your biggest opportunity is closing the gap between enquiry and response. Leads are arriving but not receiving timely, consistent engagement — creating drop-off before any qualification even begins.',
  'template', 0.95, 'reviewed',
  '[{"rank":1,"agent":"enquiry_assistant","priority":"Immediate Priority","why":"Multiple enquiry channels with slow or missed responses indicate significant lead leakage at the very first touchpoint."},{"rank":2,"agent":"sales_follow_up","priority":"High Priority","why":"Single follow-up attempts mean warm prospects go cold before a decision is reached."},{"rank":3,"agent":"appointment_coordinator","priority":"Supporting Priority","why":"Manual booking and reminders create unnecessary friction once a lead is engaged."}]',
  'template', 0.92, 'reviewed',
  'AI Enquiry Assistant handles and routes first contact → Sales Follow-Up Agent nurtures non-responders → Appointment Coordinator books and confirms calls without manual scheduling.',
  'template', 0.90, 'reviewed',
  'Before automating: compile a list of your top 15 approved FAQ answers, define what makes a lead suitable, and clarify your booking availability rules.',
  'template', 0.88, 'reviewed',
  '[{"rank":4,"agent":"lead_qualification","label":"Next Phase"},{"rank":5,"agent":"operations_reporting","label":"Next Phase"}]',
  'template', 0.85, 'reviewed',
  '{"generated_at":"2025-01-10T09:14:00Z","version":"template-v1"}',
  'completed', now() - interval '2 days', 'not_started'
),
(
  'demo_token_beta_002', 'James', 'Okafor', 'james@primetradeservices.co.uk', '07700900002', 'Prime Trade Services', 'primetradeservices.co.uk',
  true, now() - interval '5 days', false, null,
  'home_repair_local_services', 'book_more_appointments',
  ARRAY['phone_calls','referrals','online_advertising'],
  'within_same_working_day', 'staff_qualify_varies', 'staff_follow_up_when_remember',
  'essential_manual_work', ARRAY['manual_appointment_booking','appointment_reminders_rescheduling','leads_going_cold'],
  ARRAY['booking_rescheduling_appointments','following_up_with_leads','replying_to_new_enquiries'],
  'mostly_clear_not_documented',
  '{"enquiry_assistant":8,"lead_qualification":7,"sales_follow_up":10,"appointment_coordinator":16,"customer_support":4,"payment_follow_up":5,"review_reactivation":6,"operations_reporting":7}',
  'appointment_coordinator', 'sales_follow_up', 'enquiry_assistant',
  'operations_reporting', 'lead_qualification',
  '{"method":"none_required","applied":false}',
  'Your sales process depends heavily on appointments that are booked and managed manually, creating cancellation risk and follow-up gaps that cost you confirmed jobs.',
  'template', 0.95, 'reviewed',
  '[{"rank":1,"agent":"appointment_coordinator","priority":"Immediate Priority","why":"Appointments are essential to your sales process but rely entirely on manual booking and reminder effort."},{"rank":2,"agent":"sales_follow_up","priority":"High Priority","why":"Leads that do not book immediately receive inconsistent follow-up and go cold."},{"rank":3,"agent":"enquiry_assistant","priority":"Supporting Priority","why":"Phone and referral enquiries arriving outside hours are likely missed before any booking opportunity arises."}]',
  'template', 0.92, 'reviewed',
  'AI Enquiry Assistant captures and acknowledges inbound calls and messages → Sales Follow-Up Agent re-engages non-bookers → Appointment Coordinator handles confirmations, reminders, and rescheduling.',
  'template', 0.90, 'reviewed',
  'Define your booking windows clearly, prepare cancellation and rescheduling rules, and document the questions that qualify a job as suitable before sending a quote.',
  'template', 0.88, 'reviewed',
  '[{"rank":4,"agent":"operations_reporting","label":"Next Phase"},{"rank":5,"agent":"lead_qualification","label":"Next Phase"}]',
  'template', 0.85, 'reviewed',
  '{"generated_at":"2025-01-07T14:30:00Z","version":"template-v1"}',
  'completed', now() - interval '5 days', 'not_started'
),
(
  'demo_token_gamma_003', 'Priya', 'Sharma', 'priya@claritylegal.co.uk', '07700900003', 'Clarity Legal Consulting', 'claritylegal.co.uk',
  true, now() - interval '1 day', true, now() - interval '1 day',
  'professional_services_consulting', 'convert_more_leads',
  ARRAY['website_forms','email','referrals'],
  'within_one_hour', 'clear_qualification_criteria', 'consistent_multi_step_process',
  'essential_well_automated', ARRAY['outstanding_invoices_payment_chasing','too_few_reviews','inactive_leads_past_customers'],
  ARRAY['sending_invoices_payment_reminders','requesting_reviews','re_engaging_inactive_contacts'],
  'processes_clearly_documented',
  '{"enquiry_assistant":4,"lead_qualification":5,"sales_follow_up":4,"appointment_coordinator":3,"customer_support":6,"payment_follow_up":14,"review_reactivation":13,"operations_reporting":8}',
  'payment_follow_up', 'review_reactivation', 'operations_reporting',
  'customer_support', 'lead_qualification',
  '{"method":"none_required","applied":false}',
  'Your front-end processes are already relatively structured. The clearest opportunities now lie in automating payment follow-up, generating more reviews from satisfied clients, and re-engaging your existing contact base.',
  'template', 0.95, 'reviewed',
  '[{"rank":1,"agent":"payment_follow_up","priority":"Immediate Priority","why":"Outstanding invoices and manual payment chasing consume time and create cash-flow uncertainty that structured automation can resolve."},{"rank":2,"agent":"review_reactivation","priority":"High Priority","why":"Too few reviews and inactive past clients represent untapped revenue from relationships you have already built."},{"rank":3,"agent":"operations_reporting","priority":"Supporting Priority","why":"Clear processes without centralised visibility create reporting gaps that grow as the business scales."}]',
  'template', 0.92, 'reviewed',
  'Payment Follow-Up Assistant sends payment links and reminders systematically → Review and Reactivation Agent requests reviews and runs win-back sequences → Operations and Reporting Assistant provides consolidated pipeline and task visibility.',
  'template', 0.90, 'reviewed',
  'Your processes are well-documented — an advantage. Prepare your approved payment-reminder message sequence, define the timing for review requests, and identify your highest-value inactive contacts.',
  'template', 0.88, 'reviewed',
  '[{"rank":4,"agent":"customer_support","label":"Next Phase"},{"rank":5,"agent":"lead_qualification","label":"Next Phase"}]',
  'template', 0.85, 'reviewed',
  '{"generated_at":"2025-01-11T08:45:00Z","version":"template-v1"}',
  'completed', now() - interval '1 day', 'not_started'
),
(
  'demo_token_delta_004', 'Marcus', 'Webb', 'marcus@nexusgrowthagency.com', null, 'Nexus Growth Agency', 'nexusgrowthagency.com',
  true, now() - interval '3 days', false, null,
  'agency_creative_marketing', 'reduce_admin_improve_visibility',
  ARRAY['referrals','social_media_messages','email'],
  'next_working_day', 'staff_qualify_manually_consistently', 'staff_follow_up_crm',
  'important_cancellations_no_shows', ARRAY['manual_reporting_scattered_information','tasks_handovers_missed','repetitive_customer_support_requests'],
  ARRAY['updating_spreadsheets_crm_records','preparing_reports','assigning_tasks_notifying_staff'],
  'different_staff_handle_differently',
  '{"enquiry_assistant":5,"lead_qualification":6,"sales_follow_up":7,"appointment_coordinator":8,"customer_support":9,"payment_follow_up":4,"review_reactivation":5,"operations_reporting":15}',
  'operations_reporting', 'customer_support', 'appointment_coordinator',
  'sales_follow_up', 'lead_qualification',
  '{"method":"none_required","applied":false}',
  'Operational fragmentation is your primary constraint. Scattered reporting, missed handovers, and inconsistent task ownership are costing your team time and limiting your ability to scale client delivery.',
  'template', 0.95, 'reviewed',
  '[{"rank":1,"agent":"operations_reporting","priority":"Immediate Priority","why":"Scattered information, missed handovers, and manual reporting are the dominant pain points across your team."},{"rank":2,"agent":"customer_support","priority":"High Priority","why":"Repetitive client questions absorb senior time that should be directed at delivery and growth."},{"rank":3,"agent":"appointment_coordinator","priority":"Supporting Priority","why":"Cancellations and no-shows in your client-facing process create rework and scheduling gaps."}]',
  'template', 0.92, 'reviewed',
  'Operations and Reporting Assistant centralises task visibility and internal alerts → Customer Support Agent handles repetitive client queries → Appointment Coordinator manages scheduling consistency.',
  'template', 0.90, 'reviewed',
  'Before automating: agree on how tasks are owned and handed over, define which client questions can be answered from an approved FAQ, and standardise your weekly reporting format.',
  'template', 0.88, 'reviewed',
  '[{"rank":4,"agent":"sales_follow_up","label":"Next Phase"},{"rank":5,"agent":"lead_qualification","label":"Next Phase"}]',
  'template', 0.85, 'reviewed',
  '{"generated_at":"2025-01-09T11:20:00Z","version":"template-v1"}',
  'completed', now() - interval '3 days', 'not_started'
);